### Importación de bilbiotecas necesarias


In [2]:
import numpy as np

In [3]:
## ---> Funcion para definir una función de benchmark para probar 

def dtlz2(x, n_obj):
    """
    DTLZ2 test problem

    Parameters
    ----------
    x : array_like
        Decision variables
    n_obj : int
        Number of objectives

    Returns
    -------
    array_like
        Objective values
    """
    x = np.asarray(x)
    n_var = len(x)
    k = n_var - n_obj + 1

    g = np.sum((x[n_obj-1:] - 0.5)**2)

    f = np.zeros(n_obj)
    f[0] = (1 + g) * np.prod(np.cos(x[:n_obj-1] * np.pi / 2))
    for i in range(1, n_obj - 1):
        f[i] = (1 + g) * np.prod(np.cos(x[:n_obj-1-i] * np.pi / 2)) * np.sin(x[n_obj-1-i] * np.pi / 2)
    f[n_obj-1] = (1 + g) * np.sin(x[0] * np.pi / 2)

    return f


In [5]:
import numpy as np
from IPython.display import display, Latex

def mostrar_matriz_latex(matriz):
    """
    Muestra una matriz en formato LaTeX de forma visual en una celda de Jupyter/Colab.

    Parámetros:
        matriz (list of lists or np.array): La matriz que se desea mostrar.
    """
    # Asegurar que sea una matriz de numpy para facilitar el manejo
    matriz = np.array(matriz)

    # Crear el string LaTeX
    latex_str = r"\begin{bmatrix}"
    for fila in matriz:
        fila_str = " & ".join(map(str, fila))
        latex_str += fila_str + r" \\ "
    latex_str += r"\end{bmatrix}"

    # Mostrar
    display(Latex(f"$$ {latex_str} $$"))


In [8]:
# Ejemplo de uso
A = [[1, 2, 3,5],
     [4, 5, 6,8],
     [7, 8, 9,11]]

mostrar_matriz_latex(A)


<IPython.core.display.Latex object>

In [7]:
import numpy as np

# Matrices ejemplo
A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([[10, 20, 30],
              [40, 50, 60]])

# Definir permutación de columnas (por ejemplo, intercambiar la 1ra y 3ra columna)
permutacion = [2, 0, 1]  # Esto pone la 3ª columna primero, luego la 1ª, luego la 2ª

# Aplicar la permutación a las columnas
A_perm = A[:, permutacion]
B_perm = B[:, permutacion]

# Mostrar resultados
print("A original:\n", A)
print("A permutada:\n", A_perm)

print("B original:\n", B)
print("B permutada:\n", B_perm)


A original:
 [[1 2 3]
 [4 5 6]]
A permutada:
 [[3 1 2]
 [6 4 5]]
B original:
 [[10 20 30]
 [40 50 60]]
B permutada:
 [[30 10 20]
 [60 40 50]]


In [ ]:
La población de padres es: [44, 17, 8, 37, 6, 3, 2, 8, 37, 35, 29, 34, 42, 37, 48, 44, 26, 13, 32, 6, 49, 48, 11, 6, 28, 8, 45, 37, 19, 19, 3, 48, 30, 45, 40, 12, 6, 29, 42, 10, 40, 16, 17, 44, 3, 18, 31, 5, 44, 2]