Prueba de la funcion para cargar los datos de la matriz de relación operación-máquina 

In [1]:
from datos_transformacion import *

matriz_gen = cargar_matriz_operaciones_maquina('datos_maquina_operacion.txt')
print(matriz_gen.shape)
print(matriz_gen)
print(f"Imprimiendo el valor en el espacio 2,2 = {matriz_gen[1][1]}")

IndentationError: expected an indented block after 'for' statement on line 99 (datos_transformacion.py, line 100)

Imprimiendo el diccionario estructura para pasar a la función de graficación....

In [ ]:
tareas = [
    # Tarea 1 con 3 actividades 
    [ 
        {'maquina': 0, 'duracion': 5.2, 'inicio':0, 'actividad_num':1},
        {'maquina': 1, 'duracion': 7.8, 'inicio':5.2, 'actividad_num':2},
        {'maquina': 1, 'duracion': 5.5, 'inicio':13, 'actividad_num':3},  
    ],
    # Trabajo 2 con 2 actividades
    [
        {'maquina': 0, 'duracion': 3.1, 'inicio':5.2, 'actividad_num':1},
        {'maquina': 2, 'duracion': 6.2, 'inicio':0, 'actividad_num':2},
    ],
    # Trabajo 3 con 3 actividades
    [
        {'maquina': 0, 'duracion': 2.5, 'inicio':8.3, 'actividad_num':1},
        {'maquina': 2, 'duracion': 6.2, 'inicio':6.2, 'actividad_num':2},
        {'maquina': 2, 'duracion': 2.2, 'inicio':12.4, 'actividad_num':3}, 
    ],
    #Trabajo 4 con 1 actividad 
    [
        {'maquina': 1, 'duracion':3.1, 'inicio':18.5, 'actividad_num':1},
    ],
]


print(tareas)

In [8]:
# Declarando un array de numpy
arreglo = np.matrix([[1,2.1,3.2,4.5],[2,3,5,2]])
print(f"El arreglo es: {arreglo} ")
x,y = arreglo.shape
print(f"La matriz tiene {x} filas y {y} columnas")

El arreglo es: [[1.  2.1 3.2 4.5]
 [2.  3.  5.  2. ]] 
La matriz tiene 2 filas y 4 columnas


In [10]:
from datos_transformacion import *
matriz_tareas = cargar_matriz_oepraciones_tareas('tareas.txt')
print(matriz_tareas)
print(len(matriz_tareas))

[[1, 2, 3], [2, 3], [2, 3, 4], [1]]
4


In [14]:
x = [[] for y in range (len(matriz_tareas))]
print(x)

[[], [], [], []]


In [18]:
lista = [1,2,3]
array_numpy = np.array(lista)
print(array_numpy)
print(type(array_numpy))


array_2 = np.array(array_numpy)
print(array_2)
print(type(array_2))

[1 2 3]
<class 'numpy.ndarray'>
[1 2 3]
<class 'numpy.ndarray'>


# Probando la función principal

In [43]:
# Parámetros que se necesitan 
mat_op_maq = cargar_matriz_operaciones_maquina('datos_maquina_operacion.txt')
mat_op_tar = cargar_matriz_oepraciones_tareas('tareas.txt')
array_genetico = np.array([1,2,2,1,3,1,3,3,2,5])


## Codficando la función principal

In [ ]:
# ---> funcion adicional para gestionar el tiempo

In [ ]:
def transformar_datos_visualizador(mtx_oper_mach, mtx_oper_tsk, vector_gen):
    # FUNCION PARA GESTIONAR EL TIEMPO
    

    
    print(f"La matriz de maquinas-operaciones es : {mtx_oper_mach}")
    # Convirtiendo el vector generado por el genético en un array de numpy 
    vector_gen = np.array(vector_gen)
    # Genearando la lista general que contendrá todos los datos
    arreglo_visualizador = [[] for i in range(len(mtx_oper_mach))]

    # Generando la lista con cada una de las tareas 
    arreglo_tareas_genetico = [[] for i in range(len(mtx_oper_mach))]

    # Lista con la longitud de cada una de las tareas
    cortes = [len(arreglo) for arreglo in mtx_oper_tsk]

    # Haciendo una lista con las operaciones correspondientes a cada tarea
    idx_aux = 0
    for i in range(len(arreglo_tareas_genetico)):
        arreglo_tareas_genetico[i] = vector_gen[idx_aux : idx_aux + cortes[i]]
        idx_aux = idx_aux + cortes[i]

    #print(f"El array de tareas es: {mtx_oper_tsk} que es la operación a realizar")
    #print(f"El array en el genetico es: {arreglo_tareas_genetico} que contiene la máquina que la ejecutará")
    
    # Generar dos arreglos para el manejo del tiempo en las máquinas

    tiempo_maquinas = [[0.0] for _ in range(mtx_oper_mach.shape[1])]
    tiempo_tareas = [[0.0] for _ in range(len(mtx_oper_mach))]

    print(f"El array tiempo-maquinas es: {tiempo_maquinas}")
    print(f"El array tiempo-tareas es: {tiempo_tareas}")









    #print(f"Imprimiendo el array tiempo_maquinas en su declaración: {tiempo_maquinas}")
    #print(f"Imprimiendo el array tiempo_tareas en su declaración: {tiempo_tareas}")
    # Llenando el array principal con los valores que se van obteniendo
    for i_tareas in range(len(arreglo_visualizador)):  # ---> Va de 0 a 3
        print(f"---------------------- Para la tarea {i_tareas + 1}")
        for j_act in range(len(mtx_oper_tsk[i_tareas])): # ---> Va de 
            #print(f"El valor de j_act es: {j_act}")
            # Definiendo variables para cada uno de los puntos que debe contener la estructura

            num_maquina = arreglo_tareas_genetico[i_tareas][j_act]-1
            duracion_operacion = mtx_oper_mach[mtx_oper_tsk[i_tareas][j_act]-1][arreglo_tareas_genetico[i_tareas][j_act]-1]
            #print(f"La maquina actual tiene los siguientes tiempos: {tiempo_maquinas[num_maquina]} siendo de tipo {type(tiempo_maquinas[num_maquina])}")
            #print(f"La tarea actual va de acuerdo a los sigiuentes tiempo: {tiempo_tareas[i_tareas]} siendo de tipo {type(tiempo_tareas[i_tareas])}")
            punto_inicio = max(max(tiempo_maquinas[num_maquina]), max(tiempo_tareas[i_tareas]))
            
            arreglo_visualizador[i_tareas].append({'maquina': num_maquina, 
                                                   'duracion': duracion_operacion,
                                                   'inicio': punto_inicio,
                                                   'actividad_num':j_act+1,
                                                   })
            print(f"La operación: {mtx_oper_tsk[i_tareas][j_act]} será ejecutada en la máquina {num_maquina} con una duración de {duracion_operacion} e iniciando en el tiempo: {punto_inicio} y siendo la actividad: {j_act+1}")
            
            # Actualizando los tiempos de las máquinas y las tareas: Tiempo inicio + duracion
            tiempo_maquinas[num_maquina].append(tiempo_maquinas[num_maquina][-1] + duracion_operacion)
            tiempo_tareas[i_tareas].append(tiempo_tareas[i_tareas][-1] + duracion_operacion)       


    return arreglo_visualizador

## Probando la funcion principal con casos de prueba

In [144]:
transformar_datos_visualizador(mat_op_maq, mat_op_tar, array_genetico)

La matriz de maquinas-operaciones es : [[5.2 3.1 6.8]
 [2.5 7.8 1.9]
 [9.3 5.5 6.2]
 [3.1 1.2 2.2]]
El array tiempo-maquinas es: [[0.0], [0.0], [0.0]]
El array tiempo-tareas es: [[0.0], [0.0], [0.0], [0.0]]
---------------------- Para la tarea 1
La operación: 1 será ejecutada en la máquina 0 con una duración de 5.2 e iniciando en el tiempo: 0.0 y siendo la actividad: 1
La operación: 2 será ejecutada en la máquina 1 con una duración de 7.8 e iniciando en el tiempo: 5.2 y siendo la actividad: 2
La operación: 3 será ejecutada en la máquina 1 con una duración de 5.5 e iniciando en el tiempo: 13.0 y siendo la actividad: 3
---------------------- Para la tarea 2
La operación: 2 será ejecutada en la máquina 0 con una duración de 2.5 e iniciando en el tiempo: 5.2 y siendo la actividad: 1
La operación: 3 será ejecutada en la máquina 2 con una duración de 6.2 e iniciando en el tiempo: 2.5 y siendo la actividad: 2
---------------------- Para la tarea 3
La operación: 2 será ejecutada en la máquina 

[[{'maquina': 0, 'duracion': 5.2, 'inicio': 0.0, 'actividad_num': 1},
  {'maquina': 1, 'duracion': 7.8, 'inicio': 5.2, 'actividad_num': 2},
  {'maquina': 1, 'duracion': 5.5, 'inicio': 13.0, 'actividad_num': 3}],
 [{'maquina': 0, 'duracion': 2.5, 'inicio': 5.2, 'actividad_num': 1},
  {'maquina': 2, 'duracion': 6.2, 'inicio': 2.5, 'actividad_num': 2}],
 [{'maquina': 0, 'duracion': 2.5, 'inicio': 7.7, 'actividad_num': 1},
  {'maquina': 2, 'duracion': 6.2, 'inicio': 6.2, 'actividad_num': 2},
  {'maquina': 2, 'duracion': 2.2, 'inicio': 12.4, 'actividad_num': 3}],
 [{'maquina': 1, 'duracion': 3.1, 'inicio': 13.3, 'actividad_num': 1}]]

In [ ]:
import numpy as np 

matriz = np.array([[0.0] for _ in range(4)])
print(matriz)

arreglo_prueba = np.array([[1,2,3],[4,5,6]])
print(f"Arreglo de prueba {arreglo_prueba[0]} antes de la inserción")

arreglo_prueba[0] = np.append(arreglo_prueba[0], 4, axis=None)
print(f"El arreglo de prueba después de la inserción : {arreglo_prueba}")

[[0.]
 [0.]
 [0.]
 [0.]]
Arreglo de prueba [1 2 3] antes de la inserción


ValueError: could not broadcast input array from shape (4,) into shape (3,)

## Funciones de ordenamiento en python

In [ ]:
import numpy as np
# Sea el siguiente arreglo una representación matricial 
array_desordenado = np.array([[10,55,30], [11, 16, 21], [4, 23, 10]])

# Se obtienen los índices que ordenarían la matriz de acuerdo con sus índices 
indexes = np.argsort(array_desordenado[:, 1])
print(f"Lo que se obtiene del array index es: {indexes} y es de tipo: {type(indexes)}")
print(f"La matriz ordenada es: {array_desordenado[indexes]}")

Lo que se obtiene del array index es: [1 2 0] y es de tipo: <class 'numpy.ndarray'>
La matriz ordenada es: [[11 16 21]
 [ 4 23 10]
 [10 55 30]]


: 